version: '3'
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    volumes:
      - mysql_data:/var/lib/mysql

  spring-app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/example_db
      SPRING_DATASOURCE_USERNAME: example_user
      SPRING_DATASOURCE_PASSWORD: example_password

#  cloudbeaver:
#    image: dbeaver/cloudbeaver:latest
#    restart: always
#    ports:
#      - 8081:8978
#    volumes:
#      - /var/cloudbeaver/workspace:/opt/cloudbeaver/workspace
#    depends_on:
#      - mysql

volumes:
  mysql_data:
