spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/example_db}
    username: ${SPRING_DATASOURCE_USERNAME:example_user}
    password: ${SPRING_DATASOURCE_PASSWORD:example_password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  web:
    resources:
      static-locations: file:./client/build/,classpath:/static/

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub

server:
  port: ${SERVER_PORT:8080}

app:
  upload.path: /uploads/