spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/projectmg
    username: shadhin
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  web:
    resources:
      static-locations: file:./client/build/

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub

app:
  upload.path: C:\Users\Shadhin\Documents\uploads\